name: ci

on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          timeout: 10m
          script: |
            echo "Check Folder"
            ls

            echo "CD to project/cuaca-client"
            cd project/cuaca-client

            echo "Git Pull"
            git pull

            echo "CD to project"
            cd ../

            echo "Docker Compose Build"
            docker compose build --no-cache cuaca-client

            echo "Docker Compose up"
            docker compose up -d

            echo "Docker system prune"
            docker system prune -f
